# Generated by Django 3.0.6 on 2020-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='attack',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='defense',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='move',
            name='damage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='elo',
            field=models.IntegerField(),
        ),
    ]
