# Generated by Django 3.0.6 on 2020-06-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_auto_20200615_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='name',
            field=models.CharField(default='placeholder', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='name',
            field=models.CharField(default='placeholder', max_length=30),
            preserve_default=False,
        ),
    ]
