# Generated by Django 3.0.6 on 2020-06-16 11:04

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_auto_20200615_1101'),
    ]

    operations = [
    ]
